name: PR updater
description: Keep your pull requests up to date with base branch
inputs:
  token:
    required: true
    description: "Token to perform api calls"

runs:
  using: node16
  main: bin/index.js

branding:
  icon: git-pull-request
  color: green
