name: Testing

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Use Node LTS version
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 18
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run build
        run: yarn build
      - name: Run test suite
        run: yarn test

  coverage:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 16
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run build
        run: yarn build
      - name: Run coverage report
        run: yarn coverage
      - uses: actions/upload-artifact@v3
        with:
          name: coverage-data-${{ github.run_id }}
          path: |
            coverage/coverage*.json
      - name: Coverage summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/cobertura-coverage.xml
          format: 'markdown'
          output: 'both'
      - name: Add coverage PR comment
        uses: marocchino/sticky-pull-request-comment@v2.5.0
        with:
          recreate: true
          path: code-coverage-results.md
      - name: Write to job summary
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
