name: PR update

on:
  push:
    branches: master

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: update all prs
        uses: ./
        with:
          token: ${{ secrets.USER_TOKEN }}
          mode: autoupdate
